# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    #what this on signifies here is everytime theres a pull request happening on a pull request event because the branches we are merging into
    #the target branch is main we want to run the below particular job

jobs:
  build:
    #firts job we are running is to confirm that the build is succesfull that why we name it as build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4 # this command tells github to checkout to the current branch or more specifically the feature branch in our context.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: "Installing dependencies"
        run: npm i

      - name: "build command"
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Installing dependencies
        run: npm i

      - name: "Running test cases"
        run: npm run test
